---

name: Lint

on:
  pull_request:
    branches:
      - trunk
  push:
    branches:
      - trunk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: lts/*

      - name: Install
        run: npm ci

      - name: Check types
        run: npm run check-types

      - name: Lint files
        run: npm run lint
